DROP TABLE IF EXISTS zmogus;
  
CREATE TABLE zmogus (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  vardas VARCHAR(250) NOT NULL,
  role VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS preke;
  
CREATE TABLE preke (
  kodas INT AUTO_INCREMENT  PRIMARY KEY,
  pavadinimas VARCHAR(250) NOT NULL,
  salis VARCHAR(250) NOT NULL,
  kainaVnt FLOAT NOT NULL
);